
class ConfigObj:
    @staticmethod
    def generate_config(job:str, prama:str):
        config_dict = {
            "BEOL_SCRAP_S06" : {"src-schema" : "beolstg.",
                                "fab-code" : "115160",
                                "process-stage" : "BEOL",
                                "fab-id" : "S06",
                                "site-id" : "AUSZ",
                                "op_id" : None,
                                "parea" : None},
            "BEOL_SCRAP_S02" : {"src-schema" : "beolstg.",
                                "fab-code" : "115060",
                                "process-stage" : "BEOL",
                                "fab-id" : "S02",
                                "site-id" : "AUSZ",
                                "op_id" : None,
                                "parea" : None},
            "BEOL_SCRAP_S01" : {"src-schema" : "beolstg.",
                                "fab-code" : "115000",
                                "process-stage" : "BEOL",
                                "fab-id" : "S01",
                                "site-id" : "AUSZ",
                                "op_id" : None,
                                "parea" : None},
            "BEOL_OTP_MASTER_S01" : {"src-schema" : "beolstg.",
                                "fab-code" : "115000",
                                "process-stage" : "BEOL",
                                "fab-id" : "S01",
                                "site-id" : "AUS",
                                "op_id" : None,
                                "parea" : None},
            "BEOL_MASTER_S01" : {"src-schema" : "beolstg.",
                                "fab-code" : "115000",
                                "process-stage" : "BEOL",
                                "fab-id" : "S01",
                                "site-id" : "AUS",
                                "op_id" : "SKD-TEST",
                                "parea" : " and parea = '3ENEW' "},
            "BEOL_MATERIAL_S01" : {"src-schema" : "beolstg.",
                                "fab-code" : "115000",
                                "process-stage" : "BEOL",
                                "fab-id" : "S01",
                                "site-id" : "AUS",
                                "op_id" : None,
                                "parea" : None},
            "BEOL_TDF_S01" : {"src-schema" : "beolstg.",
                                "fab-code" : "115000",
                                "process-stage" : "BEOL",
                                "fab-id" : "S01",
                                "site-id" : "AUS",
                                "test-op" : ('PFL',
                                'CT1-AOI',
                                'CT2-AOI',
                                'CELLTESTER',
                                'VI',
                                'CT1',
                                'CT2'),
                                "image_file_path" : None,
                                "op_id" : None,
                                "parea" : None},
            "BEOL_QA_S01" : {"src-schema" : "beolstg.",
                                "fab-code" : "115000",
                                "process-stage" : "BEOL",
                                "fab-id" : "S01",
                                "site-id" : "AUS",
                                "op_id" : None,
                                "parea" : None},
            "BEOL_MASTER_S02" : {"src-schema" : "beolstg.",
                                "fab-code" : "115060",
                                "process-stage" : "BEOL",
                                "fab-id" : "S02",
                                "site-id" : "AUSZ",
                                "op_id" : None,
                                "parea" : None},
            "BEOL_MATERIAL_S02" : {"src-schema" : "beolstg.",
                                "fab-code" : "115060",
                                "process-stage" : "BEOL",
                                "fab-id" : "S02",
                                "site-id" : "AUSZ",
                                "op_id" : None,
                                "parea" : None},
            "BEOL_TDF_S02" : {"src-schema" : "beolstg.",
                                "fab-code" : "115060",
                                "process-stage" : "BEOL",
                                "fab-id" : "S02",
                                "site-id" : "AUSZ",
                                "test-op" : ('FD-BIM-S',
                                'CT1-AOI',
                                'LSR',
                                'CELLTESTER',
                                'VI',
                                'CT1',
                                'CT2',
                                'AUTO',
                                'CT1-AOI',
                                'CT2-AOI',
                                'DISP',
                                'FMA',
                                'LASER-CUT',
                                'LSR',
                                'LV2-CT2',
                                'PFL',
                                'POL-LSC',
                                'SCRAP',
                                'SHEETCUT',
                                'SHIPMENT',
                                'VI',
                                'VI-BLL'),
                                "image_file_path" : None,
                                "op_id" : None,
                                "parea" : None},
            "BEOL_QA_S02" : {"src-schema" : "beolstg.",
                                "fab-code" : "115060",
                                "process-stage" : "BEOL",
                                "fab-id" : "S02",
                                "site-id" : "AUSZ",
                                "op_id" : None,
                                "parea" : None},
            "BEOL_MASTER_S03" : {"src-schema" : "beolstg.",
                                "fab-code" : "115100",
                                "process-stage" : "BEOL",
                                "fab-id" : "S03",
                                "site-id" : "AUSJ",
                                "op_id" : None,
                                "parea" : None},
            "BEOL_MATERIAL_S03" : {"src-schema" : "beolstg.",
                                "fab-code" : "115100",
                                "process-stage" : "BEOL",
                                "fab-id" : "S03",
                                "site-id" : "AUSJ",
                                "op_id" : None,
                                "parea" : None},
            "BEOL_TDF_S03" : {"src-schema" : "beolstg.",
                                "fab-code" : "115100",
                                "process-stage" : "BEOL",
                                "fab-id" : "S03",
                                "site-id" : "AUSJ",
                                "test-op" : ('CELLTESTER',
                                'VI',
                                'CT1',
                                'CT2'),
                                "image_file_path" : None,
                                "op_id" : None,
                                "parea" : None},
            "BEOL_QA_S03" : {"src-schema" : "beolstg.",
                                "fab-code" : "115100",
                                "process-stage" : "BEOL",
                                "fab-id" : "S03",
                                "site-id" : "AUSJ",
                                "op_id" : None,
                                "parea" : None},
            "BEOL_OTP_MASTER_S06" : {"src-schema" : "beolstg.",
                                "fab-code" : "115160",
                                "process-stage" : "BEOL",
                                "fab-id" : "S06",
                                "site-id" : "AUS",
                                "op_id" : None,
                                "parea" : None},
            "BEOL_MASTER_S06" : {"src-schema" : "beolstg.",
                                "fab-code" : "115160",
                                "process-stage" : "BEOL",
                                "fab-id" : "S06",
                                "site-id" : "AUS",
                                "op_id" : "LEVEL2-BEOL','UNLOADER",
                                "parea" : None},
            "BEOL_MASTER_S16" : {"src-schema" : "cpbeolstg.",
                                "fab-code" : "115260",
                                "process-stage" : "BEOL",
                                "fab-id" : "S16",
                                "site-id" : "AUXM",
                                "input-op-id" : "'SCR-BRE'",
                                "ship-op-id" : "FI",
                                "op_id" : None,
                                "parea" : None,
                                "dw-schema" : "auodw."},
            "BEOL_TDF_S16" : {"src-schema" : "beolstg.",
                                "fab-code" : "115260",
                                "process-stage" : "BEOL",
                                "fab-id" : "S16",
                                "site-id" : "AUXM",
                                "test-op" : ('CELLTESTER',
                                'VI',
                                'CT1',
                                'CT2'),
                                "image_file_path" : None,
                                "op_id" : None,
                                "parea" : None},
            "BEOL_MASTER_S17" : {"src-schema" : "cpbeolstg.",
                                "fab-code" : "115270",
                                "process-stage" : "BEOL",
                                "fab-id" : "S17",
                                "site-id" : "AUXM",
                                "input-op-id" : "'SCR-BRE','CUTTING'",
                                "ship-op-id" : "FI",
                                "op_id" : None,
                                "parea" : None,
                                "dw-schema" : "auodw."},
            "BEOL_TDF_S17" : {"src-schema" : "cpbeolstg.",
                                "fab-code" : "115270",
                                "process-stage" : "BEOL",
                                "fab-id" : "S17",
                                "site-id" : "AUXM",
                                "test-op" : ('FI',
                                'CUTTING-FMA',
                                'DM',
                                'BM',
                                'LASER-REPAIR',
                                'LEVEL2',
                                'CT1',
                                'CUTTING',
                                'RWK6',
                                'SCRAP'),
                                "image_file_path" : None,
                                "op_id" : "'FI'",
                                "parea" : None},
            "BEOL_MASTER_S11" : {"src-schema" : "beolstg.",
                                "fab-code" : "115200",
                                "process-stage" : "BEOL",
                                "fab-id" : "S11",
                                "site-id" : "AUXM",
                                "op_id" : "ACL",
                                "parea" : None},
            "BEOL_MATERIAL_S11" : {"src-schema" : "beolstg.",
                                "fab-code" : "115200",
                                "process-stage" : "BEOL",
                                "fab-id" : "S11",
                                "site-id" : "AUXM",
                                "op_id" : None,
                                "parea" : None},
            "BEOL_TDF_S11" : {"src-schema" : "beolstg.",
                                "fab-code" : "115200",
                                "process-stage" : "BEOL",
                                "fab-id" : "S11",
                                "site-id" : "AUXM",
                                "test-op" : ('CT1',
                                'OCT',
                                'CELLTESTER',
                                'VI',
                                'CT1',
                                'CT2'),
                                "image_file_path" : None,
                                "op_id" : None,
                                "parea" : None},
            "BEOL_QA_S11" : {"src-schema" : "beolstg.",
                                "fab-code" : "115200",
                                "process-stage" : "BEOL",
                                "fab-id" : "S11",
                                "site-id" : "AUXM",
                                "op_id" : None,
                                "parea" : None},
            "BEOL_TDF_L6K" : {"src-schema" : "beolstg.",
                                "fab-code" : "111690",
                                "process-stage" : "BEOL",
                                "fab-id" : "L6K",
                                "site-id" : "AUKS",
                                "test-op" : ('CT1-AOI'),
                                "op_id" : ('CT1-AOI'),
                                "image_file_path" : "http://10.12.129.113:8000/TPFMA/",
                                "parea" : None},
            "BEOL_MASTER_K06" : {"src-schema" : "beolstg.",
                                "fab-code" : "117006",
                                "process-stage" : "BEOL",
                                "fab-id" : "K06",
                                "site-id" : "AUS",
                                "op_id" : "LEVEL2-BEOL','UNLOADER",
                                "parea" : None},
            "BEOL_MASTER_K01" : {"src-schema" : "beolstg.",
                                "fab-code" : "117011",
                                "process-stage" : "BEOL",
                                "fab-id" : "K01",
                                "site-id" : "AUS",
                                "op_id" : "SKD-TEST",
                                "parea" : " and parea = '3ENEW' "},
            "BEOL_MASTER_L6K" : {"src-schema" : "beolstg.",
                                "fab-code" : "111690",
                                "process-stage" : "BEOL",
                                "fab-id" : "L6K",
                                "site-id" : "AUKS",
                                "op_id" : "LEVEL2-BEOL','UNLOADER",
                                "parea" : None},
            "BEOL_MASTER_K17" : {"src-schema" : "cpbeolstg.",
                                "fab-code" : "117017",
                                "process-stage" : "BEOL",
                                "fab-id" : "K17",
                                "site-id" : "AUXM",
                                "input-op-id" : "'SCR-BRE','CUTTING'",
                                "ship-op-id" : "FI",
                                "op_id" : None,
                                "parea" : None,
                                "dw-schema" : "auodw."},
            "BEOL_TDF_K17" : {"src-schema" : "cpbeolstg.",
                                "fab-code" : "117017",
                                "process-stage" : "BEOL",
                                "fab-id" : "K17",
                                "site-id" : "AUXM",
                                "test-op" : ('FI',
                                'CUTTING-FMA',
                                'DM',
                                'BM',
                                'LASER-REPAIR',
                                'LEVEL2',
                                'CT1',
                                'CUTTING',
                                'RWK6',
                                'SCRAP'),
                                "image_file_path" : None,
                                "op_id" : "'FI'",
                                "parea" : None},
            "BEOL_SCRAP_S11" : {"src-schema" : "beolstg.",
                                "fab-code" : "115200",
                                "process-stage" : "BEOL",
                                "fab-id" : "S11",
                                "site-id" : "AUXM",
                                "op_id" : None,
                                "parea" : None}
        }
        try:
            return config_dict[job][prama]
        except Exception as e:
            print("configObj value not found")
